CREATE TABLE IF NOT EXISTS km_document_process_task (
  id BIGINT NOT NULL AUTO_INCREMENT,
  doc_id BIGINT NOT NULL,
  kb_id BIGINT DEFAULT NULL,
  user_id BIGINT DEFAULT NULL,
  task_type VARCHAR(32) NOT NULL COMMENT 'PROCESS/REPROCESS/REEMBED/PURGE',
  trigger_source VARCHAR(32) DEFAULT NULL,
  task_status VARCHAR(16) NOT NULL DEFAULT 'QUEUED' COMMENT 'QUEUED/RUNNING/SUCCESS/FAILED',
  progress INT NOT NULL DEFAULT 0,
  trace_id VARCHAR(64) DEFAULT NULL,
  task_payload_json JSON DEFAULT NULL,
  idempotency_key VARCHAR(160) DEFAULT NULL,
  source_task_id BIGINT DEFAULT NULL,
  strategy_version BIGINT DEFAULT NULL,
  target_version_no BIGINT DEFAULT NULL,
  retry_count INT NOT NULL DEFAULT 0,
  error_stage VARCHAR(32) DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  dispatch_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  dispatch_attempts INT NOT NULL DEFAULT 0,
  last_dispatch_attempt_at DATETIME DEFAULT NULL,
  published_at DATETIME DEFAULT NULL,
  worker_claim_token VARCHAR(64) DEFAULT NULL,
  worker_claim_expire_at DATETIME DEFAULT NULL,
  last_event_seq INT NOT NULL DEFAULT 0,
  last_event_id VARCHAR(64) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  started_at DATETIME DEFAULT NULL,
  finished_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_idempotency_key (idempotency_key),
  KEY idx_task_dispatch (task_status, dispatch_status, last_dispatch_attempt_at),
  KEY idx_task_doc_type (doc_id, task_type, created_at),
  KEY idx_task_user_running (user_id, trigger_source, task_type, task_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档异步处理任务表';

