ALTER TABLE km_document_process_task
  ADD COLUMN IF NOT EXISTS trigger_source VARCHAR(32) DEFAULT NULL AFTER task_type,
  ADD COLUMN IF NOT EXISTS task_payload_json JSON DEFAULT NULL AFTER trace_id,
  ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(160) DEFAULT NULL AFTER task_payload_json,
  ADD COLUMN IF NOT EXISTS source_task_id BIGINT DEFAULT NULL AFTER idempotency_key,
  ADD COLUMN IF NOT EXISTS strategy_version BIGINT DEFAULT NULL AFTER source_task_id,
  ADD COLUMN IF NOT EXISTS target_version_no BIGINT DEFAULT NULL AFTER strategy_version,
  ADD COLUMN IF NOT EXISTS error_stage VARCHAR(32) DEFAULT NULL AFTER error_message,
  ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT NULL AFTER created_at,
  ADD COLUMN IF NOT EXISTS dispatch_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS dispatch_attempts INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_dispatch_attempt_at DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS published_at DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS worker_claim_token VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS worker_claim_expire_at DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS last_event_seq INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_event_id VARCHAR(64) DEFAULT NULL;

